version: '2.4'

services:
  app:
    image: humble_audio_server:local
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - 'mysql'
      - 'redis'
    env_file:
      - '.env-local'
    ports:
      - '3030:3000/tcp'
    volumes:
      - .:/app
      - /Volumes/MegaMedia/Primus/audio.music/wp:/app/public/audio/music
    environment:
      RAILS_ENV: "development"
    command: rails s -p 3000 -b 0.0.0.0

  # MySQL
  mysql: 
    # See https://hub.docker.com/_/mysql/
    image: mysql:5.7
    # Persist the database between containers by storing it in a volume
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306/tcp"
    # No root password
    env_file:
      - '.env-local'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  cable:
    image: humble_audio_server:local
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'
    env_file:
      - '.env-local'

volumes:
  redis:
