
# Lets you change the colors in the UI

# If 'light', show white icons in playbar. If 'dark', show black icons
icons: light

bg_media: "#002240"
fg_media: "#FFF"
mode_media: "#fb5461"
link_media: "#ffee80"
folder_media: "#39d900"
bg_devices: "#003564"
fg_devices: "#80ffb5"
bg_playbar: "#00498a"
fg_playbar: "#FFBB5F"
selected_device: "#ffee80"